# Stage 0: Base image with dependencies
FROM node:18-alpine3.19 as base

# Update system packages and install necessary dependencies
RUN apk update \
    && apk upgrade \
    && apk add --no-cache chromium chromium-chromedriver libstdc++ \
    && apk add openjdk11-jre-headless  # Install Java

# Install pnpm
RUN npm install -g pnpm
RUN npm install -g wait-on
RUN npm install -g @sap/cds

# Set working directory
WORKDIR /app

# Stage 1: Build the npm package and sample apps
FROM base as build-stage

COPY ../../package.json package.json
COPY ../../pnpm-workspace.yaml pnpm-workspace.yaml

# Copy the source code
COPY . ./

# Install project dependencies
RUN pnpm install --no-frozen-lockfile

# Build the npm package and sample apps
RUN pnpm build

# Stage 2: Runtime stage for running tests
FROM base as test-stage

# Copy built files from the build-stage
COPY --from=build-stage /app /app

# Copy your script into the container
COPY ./examples/docker/start-tests.sh /start-tests.sh
RUN chmod +x /start-tests.sh

# Set environment variables for headless Chrome
ENV CHROME_BIN=/usr/bin/chromium-browser
ENV CHROME_PATH=/usr/lib/chromium/

# Install and configure Selenium Standalone Server
# RUN npm install -g selenium-standalone
# RUN selenium-standalone install

# Command to run the script
CMD ["/start-tests.sh"]