name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "external"]
assignees:
  - marianfoo
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: odata
    attributes:
      label: OData Version
      description: What OData Version are you using?
      options:
        - OData V2
        - OData V4
        - no OData Service related
    validations:
      required: true
  - type: dropdown
    id: draft
    attributes:
      label: Draft
      description: Are you using draft?
      options:
        - 'Yes'
        - 'No'
        - not relevant
    validations:
      required: true
  - type: input
    id: scenario
    attributes:
      label: Scenario
      description: In what Scenario are you using? (Fiori Elements/Freestyle, Object Page/List Report)
    validations:
      required: true
  - type: input
    id: spreadsheetuploadversion
    attributes:
      label: UI5 Spreadsheet Component
      description: What is your UI5 Spreadsheet Component Version?
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen and attach screenshots if possible?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please attach the log output described [here](https://spreadsheet-importer.com/pages/Troubleshooting/#activate-debug-mode-and-copy-error-messages)
      render: shell
    validations:
      required: true
  - type: textarea
    id: init
    attributes:
      label: Spreadsheet Component Init
      description: Please copy here how you initialize the ui5 component including all options like show [here](https://spreadsheet-importer.com/pages/GettingStarted/#extension-in-manifestjson).
      render: js
    validations:
      required: true
  - type: textarea
    id: manifest
    attributes:
      label: Manifest
      description: Please copy here the `resourceRoots` and `componentUsages` section of your manifest.json so i can make sure this config is correct.
      render: json
  - type: markdown
    attributes:
      value: |
        To make things easier for me, you can send me your metadata.xml with a link to this issue at [marian@marianzeis.de](mailto:marian@marianzeis.de). Better way would be to attach it here directly.
