/**
 * Unit tests for Util.columnMatchesType — the case-insensitive `labelTypeBrackets` column matcher.
 *
 * The bracketed technical token "[<Property>]" is compared without regard to case, so a template
 * generated server-side by an ABAP backend (which can emit element names in UPPER CASE, e.g.
 * "ORDERID [ORDERID]") re-imports identically to one generated by this component ("OrderId [OrderId]").
 * Matching stays anchored to the full "[token]" (no partial substring matches).
 */

const Util = require('../../src/controller/Util').default;

describe('Util.columnMatchesType (labelTypeBrackets, case-insensitive)', () => {
  it('matches the bracketed technical token (same case)', () => {
    expect(Util.columnMatchesType('OrderId [OrderId]', 'OrderId')).toBe(true);
  });

  it('matches case-insensitively (e.g. ABAP UPPER CASE template re-import)', () => {
    expect(Util.columnMatchesType('ORDERID [ORDERID]', 'OrderId')).toBe(true);
    expect(Util.columnMatchesType('OrderId [OrderId]', 'ORDERID')).toBe(true);
  });

  it('does not match a different property', () => {
    expect(Util.columnMatchesType('OrderId [OrderId]', 'Quantity')).toBe(false);
  });

  it('stays anchored to the full bracket token — no partial substring match', () => {
    // "[Id]" must not match inside "[PrefixId]"
    expect(Util.columnMatchesType('Some Label [PrefixId]', 'Id')).toBe(false);
    // a prefix of the token must not match either ("[Order]" vs "[OrderId]")
    expect(Util.columnMatchesType('Order [OrderId]', 'Order')).toBe(false);
  });

  it('requires the bracket token — a plain label does not match', () => {
    expect(Util.columnMatchesType('OrderId', 'OrderId')).toBe(false);
  });

  it('guards against non-string / empty column keys', () => {
    expect(Util.columnMatchesType(undefined, 'OrderId')).toBe(false);
    expect(Util.columnMatchesType(null, 'OrderId')).toBe(false);
    expect(Util.columnMatchesType(123, 'OrderId')).toBe(false);
    expect(Util.columnMatchesType('', 'OrderId')).toBe(false);
  });
});
