name: 'CLA Assistant'

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

# explicitly configure permissions
permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  CLAAssistant:
    runs-on: ubuntu-22.04
    steps:
      - name: 'CLA Assistant'
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I agree to the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: '.github/cla-signers.json'
          path-to-document: 'https://github.com/spreadsheetimporter/ui5-cc-spreadsheetimporter/blob/main/CLA.md'
          branch: 'cla'
          allowlist: 'dependabot[bot],github-actions[bot]'
          custom-notsigned-prcomment: 'Thank you for your contribution! Please read and sign our [CLA](CLA.md) by commenting "I agree to the CLA" on this PR.'
          custom-pr-sign-comment: 'I agree to the CLA'
          custom-allsigned-prcomment: 'All contributors have signed the CLA. Thank you!'
          signed-commit-message: '$contributorName has signed the CLA in $owner/$repo#$pullRequestNo'
          create-file-commit-message: 'chore: create CLA signatures file'
