name: Build and Push Docker image

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-22.04 # Use the latest Ubuntu runner
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3 - Checkout the repository content

      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0 - Set up QEMU to enable emulation of different architectures

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0 - Set up Docker Buildx for building multi-architecture images

      - name: Log in to DockerHub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0 - Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }} # Docker Hub password or token

      - name: Build and push
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0 - Build and push the Docker image
        with:
          context: . # Context for build
          file: ./examples/Dockerfile # Path to the Dockerfile
          push: true # Enable pushing the built image to Docker Hub
          tags: greatoceandrive/ui5-spreadsheet-importer-examples:latest # Tag for the built image
          platforms: linux/amd64,linux/arm64 # Platforms to build the image for

      - name: Logout from DockerHub
        if: always() # Logout from Docker Hub after pushing the image
        run: docker logout
  deploy:
    runs-on: ubuntu-22.04
    needs: build # Ensure deploy runs after the build succeeds
    environment: docker
    permissions:
      contents: read
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 # v1.2.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Clean up unused Docker resources before deploy
            docker system prune -af
            docker volume prune -f
            # Update and restart the container
            docker pull greatoceandrive/ui5-spreadsheet-importer-examples:latest
            docker stop thirsty_ritchie || true
            docker rm thirsty_ritchie || true
            docker run -d --restart unless-stopped -p 4004:4004 --name thirsty_ritchie greatoceandrive/ui5-spreadsheet-importer-examples:latest
